name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    env:
      TF_LOG: INFO

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Version
        run: terraform version
        working-directory: terraform/envs/dev

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: terraform/envs/dev

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform/envs/dev

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color
        working-directory: terraform/envs/dev

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: TF_LOG=INFO terraform apply -auto-approve -parallelism=1
        working-directory: terraform/envs/dev

